### ISSUE TITLE
Update to Node 20

### ISSUE THREAD

**Issue by stevebaxter** [swapmyvote/swapmyvote#780]
We currently require Node 14 which is pretty ancient. We should update to Node 20 which is the current LTS version.

The problem with this is that `webpacker` is not compatible with Node 20 - we get the following error:

```
[Webpacker] Compiling...
[Webpacker] Compilation failed:
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/stevebaxter/Code/swapmyvote/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/stevebaxter/Code/swapmyvote/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/stevebaxter/Code/swapmyvote/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/stevebaxter/Code/swapmyvote/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/stevebaxter/Code/swapmyvote/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/stevebaxter/Code/swapmyvote/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/stevebaxter/Code/swapmyvote/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/stevebaxter/Code/swapmyvote/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/stevebaxter/Code/swapmyvote/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/stevebaxter/Code/swapmyvote/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/stevebaxter/Code/swapmyvote/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

This is due to security improvements in Node 17 and up:

https://stackoverflow.com/a/73027407/35996

Unfortunately `webpacker` is no longer supported. Instead we should update to `jsbundling-rails` or https://github.com/shakacode/shakapacker:

https://github.com/rails/jsbundling-rails/blob/main/docs/switch_from_webpacker.md

See also #778 and #781.

**Comment by stevebaxter** [comment]
We may also want to look at using Vite rather than webpack, see https://vite-ruby.netlify.app/guide/rails.html.

**Comment by aspiers** [comment]
@stevebaxter I'm worried about other security fixes we might be missing in Node 14.x ...

**Comment by stevebaxter** [comment]
It may not be too bad as we're only using Node to compile css/js with webpack. It's not actually serving anything directly AFAIK, that's done by Rails.

So much more worried about Rails than Node TBH.

**Comment by aspiers** [comment]
Agreed for sure!

**Comment by aspiers** [comment]
@stevebaxter This appears to be blocking deployments to staging:

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       yarn install v1.22.22
       [1/5] Validating package.json...
       [2/5] Resolving packages...
       [3/5] Fetching packages...
       [4/5] Linking dependencies...
       [5/5] Building fresh packages...
       Done in 16.46s.
       I, [2024-06-15T22:50:58.626713 #2522]  INFO -- : Writing /tmp/build_19db6d22/public/assets/application-7b2e97b4ae838ab685fb1aecd5913d7b3486a5b45ba97238bbdd085b57661b84.css
       I, [2024-06-15T22:50:58.626877 #2522]  INFO -- : Writing /tmp/build_19db6d22/public/assets/application-7b2e97b4ae838ab685fb1aecd5913d7b3486a5b45ba97238bbdd085b57661b84.css.gz
       I, [2024-06-15T22:50:58.628968 #2522]  INFO -- : Writing /tmp/build_19db6d22/public/assets/home-dd1846e5ed1a9c93f45118423675a5fca865cdb7ec3e6b0168605454a7ca9def.css
       I, [2024-06-15T22:50:58.629326 #2522]  INFO -- : Writing /tmp/build_19db6d22/public/assets/home-dd1846e5ed1a9c93f45118423675a5fca865cdb7ec3e6b0168605454a7ca9def.css.gz
       I, [2024-06-15T22:50:58.630460 #2522]  INFO -- : Writing /tmp/build_19db6d22/public/assets/profile-feee7393ad7a803ba805e7dae540d255ee2467078eb6f4cf54958b49f1e8e12d.css
       I, [2024-06-15T22:50:58.630761 #2522]  INFO -- : Writing /tmp/build_19db6d22/public/assets/profile-feee7393ad7a803ba805e7dae540d255ee2467078eb6f4cf54958b49f1e8e12d.css.gz
       Warning: you are using an unstable release of Node.js (v17.9.1). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
       Compiling...
       Compilation failed:
       Browserslist: caniuse-lite is outdated. Please run:
         npx browserslist@latest --update-db
         Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
       node:internal/crypto/hash:67
         this[kHandle] = new _Hash(algorithm, xofLen);
                         ^

       Error: error:0308010C:digital envelope routines::unsupported
           at new Hash (node:internal/crypto/hash:67:19)
           at Object.createHash (node:crypto:135:10)
           at module.exports (/tmp/build_19db6d22/node_modules/webpack/lib/util/createHash.js:135:53)
           at NormalModule._initBuildHash (/tmp/build_19db6d22/node_modules/webpack/lib/NormalModule.js:417:16)
           at handleParseError (/tmp/build_19db6d22/node_modules/webpack/lib/NormalModule.js:471:10)
           at /tmp/build_19db6d22/node_modules/webpack/lib/NormalModule.js:503:5
           at /tmp/build_19db6d22/node_modules/webpack/lib/NormalModule.js:358:12
           at /tmp/build_19db6d22/node_modules/loader-runner/lib/LoaderRunner.js:373:3
           at iterateNormalLoaders (/tmp/build_19db6d22/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
           at iterateNormalLoaders (/tmp/build_19db6d22/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
           at /tmp/build_19db6d22/node_modules/loader-runner/lib/LoaderRunner.js:236:3
           at context.callback (/tmp/build_19db6d22/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
           at /tmp/build_19db6d22/node_modules/babel-loader/lib/index.js:59:71 {
         opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
         library: 'digital envelope routines',
         reason: 'unsupported',
         code: 'ERR_OSSL_EVP_UNSUPPORTED'
       }

       Node.js v17.9.1

 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.

 !     Push failed
Verifying deploy...

 !     Push rejected to swapmyvotedev.
```

I'm confused why this is failing with node 17?

**Comment by aspiers** [comment]
Ah, I guess it's because, as [you said](https://forwarddemocracy.zulipchat.com/#narrow/stream/439032-coding/topic/node.20.2F.20Ruby.20.2F.20Rails.20.2F.20Heroku.20versions/near/443618390):

> Because node 17 includes this SSL fix which breaks webpacker.

and [a recent commit of yours relaxed the node version constraint](https://forwarddemocracy.zulipchat.com/#narrow/stream/439032-coding/topic/node.20.2F.20Ruby.20.2F.20Rails.20.2F.20Heroku.20versions/near/443618447) from 14.x to >= 14.x.

**Comment by aspiers** [comment]
But with that in mind, I'm confused why we wanted this constraint to be relaxed...

**Comment by stevebaxter** [comment]
Looks like node 17 is too new as well, it has that security fix. Try using node 16.

**Comment by stevebaxter** [comment]
Looks like this may have to be <17 rather than <18.

**Comment by stevebaxter** [comment]
The reason for relaxing this is node 14 is ancient and won't even run on my ARM Mac.

**Comment by aspiers** [comment]
OK let's try 16 then!

**Comment by aspiers** [comment]
@stevebaxter I filed #987 which IIUC should unblock being able to upgrade from node 16 to 20 or even newer.

**Comment by stevebaxter** [comment]
Yep agreed.

**Comment by stevebaxter** [comment]
Done in #1035, which took us straight to Node 22 (past the Node 20 target here). `.nvmrc` is `v22.12.0`, `package.json` requires `node >=22.12`, and both CI workflows use `node-version-file: .nvmrc`. The blocker described above — Webpacker's incompatibility with Node 17+ — was removed in #1050, which replaced Webpacker with Vite.
