### ISSUE TITLE
test suite sometimes causes ERROR: duplicate key value violates unique constraint "users_pkey"

### ISSUE THREAD

**Issue by aspiers** [swapmyvote/swapmyvote#844]
First reported in https://github.com/swapmyvote/swapmyvote/pull/843#issuecomment-2183078423

Very occasionally (at least [once](https://github.com/swapmyvote/swapmyvote/actions/runs/9615467710/job/26522693064?pr=843)), we see a test failure `ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_pkey"`.  This is a Postgres error but not immediately clear whether it can _only_ happen on Postgres.  Copying the failure here in case the above GitHub action run gets expired: 

```
Running via Spring preloader in process 2360
/opt/hostedtoolcache/Ruby/3.3.2/x64/bin/ruby -I/home/runner/work/swapmyvote/swapmyvote/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.[9](https://github.com/swapmyvote/swapmyvote/actions/runs/9615467710/job/26522693064?pr=843#step:8:10).3/lib:/home/runner/work/swapmyvote/swapmyvote/vendor/bundle/ruby/3.3.0/gems/rspec-support-3.9.4/lib /home/runner/work/swapmyvote/swapmyvote/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.9.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 19830
...............................................................................................................***........................................................................................................................................................................................................................................................................................F...................................*.........................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) OmniAuth Twitter login updates existing user on subsequent login
     # but we don't support twitter logins right now, fix the bug later
     # ./spec/requests/user/callbacks_spec.rb:32

  2) OmniAuth Twitter login creates both user and identity on first login
     # but we don't support twitter logins right now, fix the bug later
     # ./spec/requests/user/callbacks_spec.rb:16

  3) OmniAuth Facebook login creates both user and identity on first login
     # but we don't support twitter logins right now, fix the bug later
     # ./spec/requests/user/callbacks_spec.rb:71

  4) User::Constituencies when configured for swaps and user is logged in GET /user/constituencies/edit works! (now write some real specs)
     # No reason given
     Failure/Error: expect(response).to have_http_status(:ok)
       expected the response to have status code :ok (200) but it was :found (302)
     # ./spec/requests/user/constituencies_spec.rb:23:in `block (5 levels) in <top (required)>'

Failures:

  1) UsersController when user is logged in GET #show returns http success
     Failure/Error: swap_with_user = create(:ready_to_swap_user2, name: "Jane")

     ActiveRecord::RecordNotUnique:
       PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_pkey"
       DETAIL:  Key (id)=(111) already exists.
     # <internal:kernel>:90:in `tap'
     # ./spec/controllers/users_controller_spec.rb:31:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::UniqueViolation:
     #   ERROR:  duplicate key value violates unique constraint "users_pkey"
     #   DETAIL:  Key (id)=(111) already exists.
     #   <internal:kernel>:90:in `tap'

Top 3 slowest examples ([10](https://github.com/swapmyvote/swapmyvote/actions/runs/9615467710/job/26522693064?pr=843#step:8:11).45 seconds, 51.8% of total time):
  layouts/application in a by-election matches snapshot
    5.34 seconds ./spec/views/layouts/application.html.haml_spec.rb:5
  user/constituencies/edit.html.haml asks for constituency
    4.95 seconds ./spec/views/user/constituencies/edit.html.haml_spec.rb:6
  Db::Fixtures::ElectoralCommissionParties#each each register entry is expected to have key "RegisterName"
    0.16[11](https://github.com/swapmyvote/swapmyvote/actions/runs/9615467710/job/26522693064?pr=843#step:8:12)8 seconds ./spec/db/fixtures/electoral_commission_parties_spec.rb:[12](https://github.com/swapmyvote/swapmyvote/actions/runs/9615467710/job/26522693064?pr=843#step:8:13)

Top 3 slowest example groups:
  user/constituencies/edit.html.haml
    4.95 seconds average (4.95 seconds / 1 example) ./spec/views/user/constituencies/edit.html.haml_spec.rb:3
  layouts/application
    2.68 seconds average (5.36 seconds / 2 examples) ./spec/views/layouts/application.html.haml_spec.rb:3
  user/swaps/new
    0.14112 seconds average (0.14112 seconds / 1 example) ./spec/views/user/swaps/new.html.haml_spec.rb:3

Finished in 20.19 seconds (files took 3.85 seconds to load)
456 examples, 1 failure, 4 pending

Failed examples:

rspec ./spec/controllers/users_controller_spec.rb:30 # UsersController when user is logged in GET #show returns http success

Randomized with seed 19830

Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
Coverage report generated for RSpec to /home/runner/work/swapmyvote/swapmyvote/coverage. 912 / [13](https://github.com/swapmyvote/swapmyvote/actions/runs/9615467710/job/26522693064?pr=843#step:8:14)07 LOC (69.78%) covered.
/opt/hostedtoolcache/Ruby/3.3.2/x64/bin/ruby -I/home/runner/work/swapmyvote/swapmyvote/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.9.3/lib:/home/runner/work/swapmyvote/swapmyvote/vendor/bundle/ruby/3.3.0/gems/rspec-support-3.9.4/lib /home/runner/work/swapmyvote/swapmyvote/vendor/bundle/ruby/3.3.0/gems/rspec-core-3.9.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
Error: Process completed with exit code 1.
```

**Comment by aspiers** [comment]
Copying comment from

I guess it's related to rspec's random ordering of tests, because it vanished when I reran the job.  If so, in theory it's reproducible via:

    rspec --seed 19830

but that would require Postgres of course.

It comes from:

https://github.com/swapmyvote/swapmyvote/blob/93bf8d42cd2908d34e18c24e1ce08319030f948f/spec/controllers/users_controller_spec.rb#L31

which refers to a test user in the factory:

https://github.com/swapmyvote/swapmyvote/blob/93bf8d42cd2908d34e18c24e1ce08319030f948f/spec/factories/user.rb#L14-L15

So somehow that user must have already been created somehow.  Presumably not from seeds, since then that test would always fail on the `create`.  So from another test?  Could it have come from here maybe?

https://github.com/swapmyvote/swapmyvote/blob/93bf8d42cd2908d34e18c24e1ce08319030f948f/spec/factories/swaps.rb#L5

**Comment by aspiers** [comment]
The schema only imposes two uniqueness constraints for `User`:

https://github.com/swapmyvote/swapmyvote/blob/93bf8d42cd2908d34e18c24e1ce08319030f948f/db/schema.rb#L134-L136

However there's also one in the model:

https://github.com/swapmyvote/swapmyvote/blob/93bf8d42cd2908d34e18c24e1ce08319030f948f/app/models/user.rb#L33-L34

I'm not sure if Rails is smart enough to create a PG uniqueness constraint from that.
