### ISSUE TITLE
5 unit tests broken locally

### ISSUE THREAD

**Issue by baob** [swapmyvote/swapmyvote#845]
Failed examples:

rspec ./spec/controllers/users_controller_spec.rb:30 # UsersController when user is logged in GET #show returns http success
rspec ./spec/views/layouts/application.html.haml_spec.rb:17 # layouts/application in a general election matches snapshot
rspec ./spec/views/layouts/application.html.haml_spec.rb:5 # layouts/application in a by-election matches snapshot
rspec ./spec/mailers/user_mailer_spec.rb:15 # UserMailer swap_cancelled sends email if swap_with is blank
rspec ./spec/mailers/user_mailer_spec.rb:8 # UserMailer swap_cancelled sends email if swap_with is not blank

**Comment by baob** [comment]
```
  1) UsersController when user is logged in GET #show returns http success
     Failure/Error: = link_to "Click here to confirm this swap!", user_url(log_in_with: @user.provider)

     ActionView::Template::Error:
       Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
     # ./app/views/user_mailer/confirm_swap.html.haml:12:in `_app_views_user_mailer_confirm_swap_html_haml__4512453047601833194_34120'
     # ./app/mailers/user_mailer.rb:24:in `confirm_swap'
     # /Users/Andy.Roberts/.rvm/gems/ruby-3.3.2@swapmyvote/gems/actiontext-6.1.7.8/lib/action_text/rendering.rb:20:in `with_renderer'
     # /Users/Andy.Roberts/.rvm/gems/ruby-3.3.2@swapmyvote/gems/actiontext-6.1.7.8/lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
     # <internal:kernel>:90:in `tap'
     # ./app/models/user.rb:172:in `swap_with_user_id'
     # ./spec/controllers/users_controller_spec.rb:34:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
     #   ./app/views/user_mailer/confirm_swap.html.haml:12:in `_app_views_user_mailer_confirm_swap_html_haml__4512453047601833194_34120'

```
```
  2) layouts/application in a by-election matches snapshot
     Failure/Error: expect(rendered).to match_snapshot("application_by_election")

       Diff:
       @@ -42,7 +42,7 @@
              },
              cookie: {
                name: "_swapmyvote_cookie_consent",
       -        domain: "localhost"
       +        domain: ""
              }
            });
          });

     # ./spec/views/layouts/application.html.haml_spec.rb:12:in `block (3 levels) in <top (required)>'
```

```
  3) layouts/application in a general election matches snapshot
     Failure/Error: expect(rendered).to match_snapshot("application_general")

       Diff:
       @@ -42,7 +42,7 @@
              },
              cookie: {
                name: "_swapmyvote_cookie_consent",
       -        domain: "localhost"
       +        domain: ""
              }
            });
          });

     # ./spec/views/layouts/application.html.haml_spec.rb:24:in `block (3 levels) in <top (required)>'
```

```
  4) UserMailer swap_cancelled sends email if swap_with is not blank
     Failure/Error: = link_to "Find another vote swapping partner - log in to swapmyvote.uk now.", user_url(log_in_with: @user.provider)

     ActionView::Template::Error:
       Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
     # ./app/views/user_mailer/swap_cancelled.haml:13:in `_app_views_user_mailer_swap_cancelled_haml__339687746844445379_53980'
     # ./app/mailers/user_mailer.rb:45:in `swap_cancelled'
     # /Users/Andy.Roberts/.rvm/gems/ruby-3.3.2@swapmyvote/gems/actiontext-6.1.7.8/lib/action_text/rendering.rb:20:in `with_renderer'
     # /Users/Andy.Roberts/.rvm/gems/ruby-3.3.2@swapmyvote/gems/actiontext-6.1.7.8/lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
     # <internal:kernel>:90:in `tap'
     # ./spec/mailers/user_mailer_spec.rb:11:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
     #   ./app/views/user_mailer/swap_cancelled.haml:13:in `_app_views_user_mailer_swap_cancelled_haml__339687746844445379_53980'
```

```
  5) UserMailer swap_cancelled sends email if swap_with is blank
     Failure/Error: = link_to "Find another vote swapping partner - log in to swapmyvote.uk now.", user_url(log_in_with: @user.provider)

     ActionView::Template::Error:
       Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
     # ./app/views/user_mailer/swap_cancelled.haml:13:in `_app_views_user_mailer_swap_cancelled_haml__339687746844445379_53980'
     # ./app/mailers/user_mailer.rb:45:in `swap_cancelled'
     # /Users/Andy.Roberts/.rvm/gems/ruby-3.3.2@swapmyvote/gems/actiontext-6.1.7.8/lib/action_text/rendering.rb:20:in `with_renderer'
     # /Users/Andy.Roberts/.rvm/gems/ruby-3.3.2@swapmyvote/gems/actiontext-6.1.7.8/lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
     # <internal:kernel>:90:in `tap'
     # ./spec/mailers/user_mailer_spec.rb:18:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ArgumentError:
     #   Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
     #   ./app/views/user_mailer/swap_cancelled.haml:13:in `_app_views_user_mailer_swap_cancelled_haml__339687746844445379_53980'
```

**Comment by baob** [comment]
@aspiers are you seeing these running guard locally ?

**Comment by baob** [comment]
Seems there's a fix already, not obviously documented.
